# Generated by Django 3.2.13 on 2022-06-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procesamiento', '0003_alter_registrocovid_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAutores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Nombre_autor', models.CharField(max_length=100, null=True, verbose_name='Nombre del autor')),
                ('Descripcion_autor', models.CharField(max_length=200, null=True, verbose_name='Descripción del autor')),
                ('Universidad_autor', models.CharField(max_length=200, null=True, verbose_name='Universidad autor')),
                ('Contacto_autor', models.CharField(max_length=200, null=True, verbose_name='Universidad autor')),
            ],
            options={
                'verbose_name': 'Información de autor',
                'verbose_name_plural': 'Información de autores',
            },
        ),
    ]
