# Generated by Django 3.2.13 on 2022-06-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procesamiento', '0004_infoautores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoautores',
            name='Contacto_autor',
            field=models.CharField(max_length=200, null=True, verbose_name='Contacto autor'),
        ),
    ]
